name: flutter_firebase
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.20
  universal_html: ^2.0.7
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  pdf: ^3.6.1
  path_provider: ^2.0.11
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/back.jpg
    - lib/images/sign.jpg
    - lib/images/loading.gif
    - lib/images/cook.png

  fonts:
    - family: SedanSC
      fonts:
        - asset: lib/fonts/SedanSC-Regular.ttf
